// TEF Canada REAL format bank (Nouveau TEF: 40 Q / 40 min listening, 40 Q / 60 min reading)
// FR = exam material, EN = translation. Sections mirror the official numbering.

export const listeningSections = [
  { id: "A", range: "Q1–4", en: "Match conversations to pictures", fr: "Associer conversations et dessins", audioNote: "Short dialogue → which picture?" },
  { id: "B", range: "Q5–8", en: "Public announcements", fr: "Annonces publiques", audioNote: "One announcement → one question" },
  { id: "C", range: "Q9–14", en: "Answering-machine messages", fr: "Messages sur répondeur", audioNote: "Who called and why?" },
  { id: "D", range: "Q15–20", en: "Street interviews (3 choices)", fr: "Micros-trottoirs (3 choix)", audioNote: "What is the person's opinion?" },
  { id: "E", range: "Q21–22", en: "Radio chronicles", fr: "Chroniques", audioNote: "Draw a conclusion" },
  { id: "F", range: "Q23–30", en: "Interviews (2 questions each)", fr: "Interviews (2 questions)", audioNote: "One interview → answer both" },
  { id: "G", range: "Q31–40", en: "Report + assorted documents", fr: "Reportage + documents divers", audioNote: "Find the precise detail" },
];

export const listeningItems = [
  // ---- A Q1-4 picture matching (choices = scene descriptions) ----
  { n: 1, section: "A", topic: "Pictures / Dessins",
    audio: "Bonjour, je voudrais une baguette bien cuite et deux croissants, s'il vous plaît. — Ça fera trois euros cinquante.",
    audioEn: "Hello, I'd like a well-baked baguette and two croissants, please. — That'll be three-fifty.",
    q: "À quel dessin correspond cette conversation ?", qEn: "Which picture matches this conversation?",
    choices: ["À la boulangerie", "À la poste", "À la gare", "À la pharmacie"],
    choicesEn: ["At the bakery", "At the post office", "At the station", "At the pharmacy"],
    answer: 0, explain: "Baguette + croissants + price = bakery. Listen for the key nouns.", explainFr: "Baguette + croissants + prix = boulangerie. Repérez les noms clés." },
  { n: 2, section: "A", topic: "Pictures / Dessins",
    audio: "Mon vol pour Montréal a du retard et ma valise n'est pas arrivée. Où dois-je faire une réclamation ? — Au comptoir des bagages, porte B.",
    audioEn: "My flight to Montreal is delayed and my suitcase didn't arrive. Where do I file a claim? — At the baggage counter, gate B.",
    q: "À quel dessin correspond cette conversation ?", qEn: "Which picture matches this conversation?",
    choices: ["Au restaurant", "À l'aéroport", "Chez le médecin", "Au cinéma"],
    choicesEn: ["At the restaurant", "At the airport", "At the doctor's", "At the cinema"],
    answer: 1, explain: "Vol + valise + réclamation = airport. Vol/retard/valise are TEF airport markers.", explainFr: "Vol + valise + réclamation = aéroport. Marqueurs : vol, retard, valise." },
  { n: 3, section: "A", topic: "Pictures / Dessins",
    audio: "Vous avez choisi ? — Oui, je prends le menu du jour avec la soupe en entrée. — Et comme boisson ? — Juste de l'eau.",
    audioEn: "Have you decided? — Yes, I'll have the set menu with soup to start. — And to drink? — Just water.",
    q: "À quel dessin correspond cette conversation ?", qEn: "Which picture matches this conversation?",
    choices: ["Au supermarché", "À la banque", "Au restaurant", "À l'hôtel"],
    choicesEn: ["At the supermarket", "At the bank", "At the restaurant", "At the hotel"],
    answer: 2, explain: "Menu du jour + entrée + boisson = restaurant.", explainFr: "Menu du jour + entrée + boisson = restaurant." },
  { n: 4, section: "A", topic: "Pictures / Dessins",
    audio: "Depuis quand avez-vous ces douleurs ? — Depuis trois jours, surtout le soir. — Je vais vous prescrire un traitement de sept jours.",
    audioEn: "How long have you had this pain? — Three days, mostly evenings. — I'll prescribe a seven-day treatment.",
    q: "À quel dessin correspond cette conversation ?", qEn: "Which picture matches this conversation?",
    choices: ["Chez le coiffeur", "Au stade", "Chez le médecin", "À l'école"],
    choicesEn: ["At the hairdresser's", "At the stadium", "At the doctor's", "At school"],
    answer: 2, explain: "Douleurs + prescrire + traitement = doctor.", explainFr: "Douleurs + prescrire + traitement = médecin." },

  // ---- B Q5-8 announcements ----
  { n: 5, section: "B", topic: "Announcements / Annonces",
    audio: "Attention voyageurs, le train à destination de Lyon partira du quai numéro trois dans cinq minutes.",
    audioEn: "Attention passengers, the Lyon train departs platform three in five minutes.",
    q: "De quel quai part le train ?", qEn: "Which platform does the train leave from?",
    choices: ["Quai numéro un", "Quai numéro deux", "Quai numéro trois", "Quai numéro cinq"],
    choicesEn: ["Platform 1", "Platform 2", "Platform 3", "Platform 5"],
    answer: 2, explain: "Trap: 5 = minutes, not the platform.", explainFr: "Piège : 5 = les minutes, pas le quai." },
  { n: 6, section: "B", topic: "Announcements / Annonces",
    audio: "Demain, le ciel sera nuageux le matin, avec des éclaircies l'après-midi et des températures autour de dix-huit degrés.",
    audioEn: "Tomorrow: cloudy morning, sunny spells afternoon, around eighteen degrees.",
    q: "Quel temps fera-t-il l'après-midi ?", qEn: "What is the afternoon weather?",
    choices: ["Il pleuvra", "Il y aura des éclaircies", "Il neigera", "Il fera froid"],
    choicesEn: ["Rain", "Sunny spells", "Snow", "Cold"],
    answer: 1, explain: "Éclaircies = sunny spells.", explainFr: "Éclaircies = sunny spells." },
  { n: 7, section: "B", topic: "Announcements / Annonces",
    audio: "En raison de travaux, la ligne quatre est interrompue entre les stations Châtelet et Gare de l'Est jusqu'à dimanche inclus.",
    audioEn: "Due to works, line four is interrupted between Châtelet and Gare de l'Est until Sunday inclusive.",
    q: "Quelle est la situation ?", qEn: "What is the situation?",
    choices: ["Grève totale", "Ligne 4 partiellement interrompue", "Retard de 5 minutes", "Nouvelle ligne"],
    choicesEn: ["Total strike", "Line 4 partly interrupted", "5-min delay", "New line"],
    answer: 1, explain: "En raison de = because of. Note the two stations + deadline.", explainFr: "En raison de = à cause de. Retiens les deux stations + délai." },
  { n: 8, section: "B", topic: "Announcements / Annonces",
    audio: "Pour tout achat supérieur à cinquante euros, vous bénéficiez d'une remise de dix pour cent sur présentation de ce coupon.",
    audioEn: "For purchases over fifty euros, get ten percent off with this coupon.",
    q: "Condition de la remise ?", qEn: "Discount condition?",
    choices: ["Acheter pour plus de 50 €", "Payer en espèces", "Venir dimanche", "Acheter en ligne"],
    choicesEn: ["Spend over €50", "Pay cash", "Come Sunday", "Buy online"],
    answer: 0, explain: "Supérieur à + bénéficier de = classic TEF vocab.", explainFr: "Supérieur à + bénéficier de = vocab TEF classique." },

  // ---- C Q9-14 answering machine ----
  { n: 9, section: "C", topic: "Answering machine / Répondeur",
    audio: "Salut, c'est Julien ! Je confirme le dîner de samedi chez moi, à vingt heures. Apporte juste le dessert. Bisous !",
    audioEn: "Hi, it's Julien! Confirming Saturday dinner at mine, 8pm. Just bring dessert. Kisses!",
    q: "Pourquoi Julien appelle-t-il ?", qEn: "Why is Julien calling?",
    choices: ["Annuler le dîner", "Confirmer le dîner de samedi", "Demander une adresse", "Proposer un cinéma"],
    choicesEn: ["Cancel dinner", "Confirm Saturday dinner", "Ask for an address", "Suggest a movie"],
    answer: 1, explain: "Tutoiement + 'Bisous' = a friend. Purpose: confirm, not cancel.", explainFr: "Tutoiement + « Bisous » = un ami. But : confirmer, pas annuler." },
  { n: 10, section: "C", topic: "Answering machine / Répondeur",
    audio: "Bonjour, le cabinet du docteur Leroy. Nous vous rappelons votre rendez-vous de demain à neuf heures trente. Merci d'apporter votre carte vitale.",
    audioEn: "Hello, Dr Leroy's office. Reminding you of tomorrow's 9:30 appointment. Please bring your health card.",
    q: "Quel est l'objet de l'appel ?", qEn: "What is the call about?",
    choices: ["Un rappel de rendez-vous médical", "Une offre commerciale", "Une invitation", "Une erreur de numéro"],
    choicesEn: ["A medical appointment reminder", "A sales offer", "An invitation", "A wrong number"],
    answer: 0, explain: "Formal tone + rendez-vous + carte vitale = medical office.", explainFr: "Ton formel + rendez-vous + carte vitale = cabinet médical." },
  { n: 11, section: "C", topic: "Answering machine / Répondeur",
    audio: "Bonjour, Chronopost. Votre colis n'a pas pu être livré. Il est disponible au point relais dès demain avec une pièce d'identité.",
    audioEn: "Hello, Chronopost. Your parcel could not be delivered. Available at the pickup point from tomorrow with ID.",
    q: "Que doit faire la personne ?", qEn: "What must the person do?",
    choices: ["Attendre le livreur", "Retirer le colis au point relais avec ID", "Payer en ligne", "Renvoyer le colis"],
    choicesEn: ["Wait for the driver", "Collect at pickup point with ID", "Pay online", "Return it"],
    answer: 1, explain: "Point relais + pièce d'identité are the actionable details.", explainFr: "Point relais + pièce d'identité = les infos d'action." },
  { n: 12, section: "C", topic: "Answering machine / Répondeur",
    audio: "Bonjour, ici Sophie des ressources humaines. Votre entretien d'embauche est fixé à lundi quatorze heures. Présentez-vous avec votre CV et une pièce d'identité.",
    audioEn: "Hello, Sophie from HR. Your job interview is Monday at 2pm. Come with your CV and ID.",
    q: "De quoi s'agit-il ?", qEn: "What is this about?",
    choices: ["Un entretien d'embauche lundi 14h", "Un licenciement", "Une formation en ligne", "Un stage annulé"],
    choicesEn: ["A job interview Monday 2pm", "A dismissal", "Online training", "A cancelled internship"],
    answer: 0, explain: "Ressources humaines + entretien + CV = hiring.", explainFr: "RH + entretien + CV = embauche." },
  { n: 13, section: "C", topic: "Answering machine / Répondeur",
    audio: "Oui bonjour, agence Fontaine. Le propriétaire peut vous faire visiter l'appartement vendredi à dix-sept heures. Rappelez-nous pour confirmer.",
    audioEn: "Hello, Fontaine agency. The owner can show you the apartment Friday at 5pm. Call back to confirm.",
    q: "Que propose l'agence ?", qEn: "What does the agency offer?",
    choices: ["Une visite vendredi à 17h", "Une baisse de loyer", "Un déménagement gratuit", "Un préavis"],
    choicesEn: ["A viewing Friday 5pm", "A rent reduction", "Free moving", "A notice"],
    answer: 0, explain: "Visiter + confirmer par rappel = viewing arrangement.", explainFr: "Visiter + rappeler pour confirmer = visite." },
  { n: 14, section: "C", topic: "Answering machine / Répondeur",
    audio: "Offre exceptionnelle ! Moins trente pour cent sur tous les canapés ce week-end seulement. Venez vite en magasin, premier arrivé, premier servi !",
    audioEn: "Exceptional offer! Thirty percent off all sofas this weekend only. Hurry in, first come first served!",
    q: "Qui laisse ce message ?", qEn: "Who leaves this message?",
    choices: ["Un ami", "Un commercial", "Un médecin", "La mairie"],
    choicesEn: ["A friend", "A salesperson", "A doctor", "The town hall"],
    answer: 1, explain: "Enthusiastic tone + offre/pour cent/premier arrivé = sales.", explainFr: "Ton enthousiaste + offre/pour cent = commercial." },

  // ---- D Q15-20 micro-trottoir (3 choices) ----
  { n: 15, section: "D", topic: "Street opinion / Micro-trottoir",
    audio: "Moi, le télétravail, j'adore : je gagne deux heures de transport par jour. Le seul problème, c'est que je vois moins mes collègues.",
    audioEn: "Me, remote work, I love it: I save two commuting hours a day. Only problem: I see colleagues less.",
    q: "Quel est son avis ?", qEn: "What is their opinion?",
    choices: ["Favorable avec une nuance", "Totalement contre", "Sans opinion"],
    choicesEn: ["Favorable with a nuance", "Totally against", "No opinion"],
    answer: 0, explain: "J'adore + le seul problème = favorable with reservation.", explainFr: "J'adore + le seul problème = favorable avec nuance." },
  { n: 16, section: "D", topic: "Street opinion / Micro-trottoir",
    audio: "Les pistes cyclables, c'est bien, mais il y en a trop peu. Pour aller travailler à vélo, c'est encore dangereux.",
    audioEn: "Bike lanes are good, but there are too few. Cycling to work is still dangerous.",
    q: "Que pense-t-elle ?", qEn: "What does she think?",
    choices: ["Il faut plus de pistes cyclables", "Il faut interdire le vélo", "Tout va bien"],
    choicesEn: ["More bike lanes needed", "Bikes should be banned", "Everything is fine"],
    answer: 0, explain: "C'est bien, mais + trop peu = wants more.", explainFr: "C'est bien, mais + trop peu = en veut plus." },
  { n: 17, section: "D", topic: "Street opinion / Micro-trottoir",
    audio: "Sept Français sur dix ? Ça ne m'étonne pas. Sans l'anglais, je n'aurais jamais eu mon poste actuel.",
    audioEn: "Seven out of ten French? Doesn't surprise me. Without English I'd never have my current job.",
    q: "Sa position ?", qEn: "Their position?",
    choices: ["L'anglais est indispensable au travail", "L'anglais est inutile", "Il ne parle pas anglais"],
    choicesEn: ["English is essential at work", "English is useless", "He doesn't speak English"],
    answer: 0, explain: "Ça ne m'étonne pas + personal proof = agrees with the study.", explainFr: "Ça ne m'étonne pas + preuve perso = d'accord avec l'étude." },
  { n: 18, section: "D", topic: "Street opinion / Micro-trottoir",
    audio: "Franchement, les écrans chez les petits, c'est une catastrophe. Mon fils de quatre ans ne joue plus dehors.",
    audioEn: "Honestly, screens for little kids is a disaster. My four-year-old no longer plays outside.",
    q: "Quel est son avis ?", qEn: "What is their opinion?",
    choices: ["Contre les écrans chez les jeunes enfants", "Pour les écrans à tout âge", "Indifférent"],
    choicesEn: ["Against screens for young children", "For screens at all ages", "Indifferent"],
    answer: 0, explain: "Catastrophe + example = strongly against.", explainFr: "Catastrophe + exemple = fermement contre." },
  { n: 19, section: "D", topic: "Street opinion / Micro-trottoir",
    audio: "La semaine de quatre jours ? Pourquoi pas, mais il faudra prouver que la production ne baisse pas.",
    audioEn: "The four-day week? Why not, but we'll have to prove output doesn't drop.",
    q: "Que dit-il ?", qEn: "What does he say?",
    choices: ["Ouvert, sous condition", "Fermement opposé", "Déjà convaincu à 100%"],
    choicesEn: ["Open, with a condition", "Firmly opposed", "Already 100% convinced"],
    answer: 0, explain: "Pourquoi pas, mais + condition = open with reservation.", explainFr: "Pourquoi pas, mais + condition = ouvert avec réserve." },
  { n: 20, section: "D", topic: "Street opinion / Micro-trottoir",
    audio: "Depuis que la boulangerie du quartier a fermé, je dois prendre ma voiture pour tout. C'est vraiment dommage pour les commerces locaux.",
    audioEn: "Since the neighbourhood bakery closed, I need my car for everything. Really a shame for local shops.",
    q: "Que regrette-t-elle ?", qEn: "What does she regret?",
    choices: ["La fermeture des commerces de proximité", "Le prix du pain", "La circulation"],
    choicesEn: ["Closing of local shops", "Bread prices", "Traffic"],
    answer: 0, explain: "Depuis que... a fermé + dommage = regrets closures.", explainFr: "Depuis que... a fermé + dommage = regrette les fermetures." },

  // ---- E Q21-22 chronicles ----
  { n: 21, section: "E", topic: "Chronicle / Chronique",
    audio: "En 1889, pour l'Exposition universelle, un ingénieur propose une tour de fer de trois cents mètres. On le traite de fou. Aujourd'hui, sept millions de visiteurs montent chaque année à la tour Eiffel.",
    audioEn: "In 1889, for the World's Fair, an engineer proposes a 300-metre iron tower. He's called crazy. Today seven million visitors climb the Eiffel Tower yearly.",
    q: "Que peut-on déduire ?", qEn: "What can be concluded?",
    choices: ["Une idée moquée peut devenir un symbole", "La tour va être démolie", "L'ingénieur a échoué", "L'exposition a été annulée"],
    choicesEn: ["A mocked idea can become a symbol", "The tower will be demolished", "The engineer failed", "The fair was cancelled"],
    answer: 0, explain: "Traité de fou → 7M visitors = mocked idea became a symbol.", explainFr: "Traité de fou → 7M visiteurs = idée moquée devenue symbole." },
  { n: 22, section: "E", topic: "Chronicle / Chronique",
    audio: "Les abeilles disparaissent : en vingt ans, un tiers des colonies s'est effondré. Or, un tiers de notre alimentation dépend de leur pollinisation.",
    audioEn: "Bees are vanishing: in twenty years a third of colonies collapsed. Yet a third of our food depends on their pollination.",
    q: "Quelle conclusion ?", qEn: "What conclusion?",
    choices: ["La disparition des abeilles menace l'alimentation", "Les abeilles sont en bonne santé", "Il faut plus de pesticides", "L'alimentation ne dépend de rien"],
    choicesEn: ["Bee loss threatens food", "Bees are healthy", "More pesticides needed", "Food depends on nothing"],
    answer: 0, explain: "Un tiers effondré + un tiers dépend = threat. Or = logical link.", explainFr: "Un tiers effondré + un tiers dépend = menace. Or = lien logique." },

  // ---- F Q23-30 interviews (4 interviews x 2 Qs, shared audio) ----
  { n: 23, section: "F", group: "IV1", topic: "Interview – chef",
    audio: "Journaliste : Pourquoi avoir ouvert votre restaurant à Montréal ? — Chef : Parce qu'ici les produits sont frais toute l'année et les clients curieux. Ma spécialité, c'est le canard à l'érable, un mélange France-Québec.",
    audioEn: "Journalist: Why open your restaurant in Montreal? — Chef: Because produce is fresh year-round and clients are curious. My speciality is maple duck, a France-Quebec mix.",
    q: "Pourquoi Montréal ?", qEn: "Why Montreal?",
    choices: ["Produits frais et clients curieux", "Loyers bas uniquement", "Proximité de la France", "Manque de concurrence"],
    choicesEn: ["Fresh produce, curious clients", "Low rents only", "Near France", "No competition"],
    answer: 0, explain: "Answer sits in the first sentence after the question.", explainFr: "La réponse est dans la 1re phrase après la question." },
  { n: 24, section: "F", group: "IV1", topic: "Interview – chef",
    audio: "Journaliste : Pourquoi avoir ouvert votre restaurant à Montréal ? — Chef : Parce qu'ici les produits sont frais toute l'année et les clients curieux. Ma spécialité, c'est le canard à l'érable, un mélange France-Québec.",
    audioEn: "Journalist: Why open your restaurant in Montreal? — Chef: Because produce is fresh year-round and clients are curious. My speciality is maple duck, a France-Quebec mix.",
    q: "Quelle est sa spécialité ?", qEn: "What is his speciality?",
    choices: ["Le canard à l'érable", "La poutine classique", "Le croissant au beurre", "La tourtière"],
    choicesEn: ["Maple duck", "Classic poutine", "Butter croissant", "Tourtière"],
    answer: 0, explain: "Second question = precise detail (canard à l'érable).", explainFr: "2e question = détail précis (canard à l'érable)." },
  { n: 25, section: "F", group: "IV2", topic: "Interview – athlete",
    audio: "Journaliste : Comment préparez-vous les Jeux ? — Athlète : Je m'entraîne six jours sur sept, avec deux séances par jour. Le plus dur, c'est la récupération : dormir neuf heures et bien manger.",
    audioEn: "Journalist: How do you prepare for the Games? — Athlete: I train six days out of seven, two sessions daily. Hardest is recovery: nine hours sleep and good food.",
    q: "Quel est son rythme ?", qEn: "What is their routine?",
    choices: ["6 jours sur 7, 2 séances par jour", "3 jours par semaine", "1 séance par mois", "Tous les jours sans repos"],
    choicesEn: ["6/7 days, 2 sessions daily", "3 days a week", "1 session a month", "Every day, no rest"],
    answer: 0, explain: "Six jours sur sept + deux séances. Numbers decide.", explainFr: "Six jours sur sept + deux séances. Les nombres décident." },
  { n: 26, section: "F", group: "IV2", topic: "Interview – athlete",
    audio: "Journaliste : Comment préparez-vous les Jeux ? — Athlète : Je m'entraîne six jours sur sept, avec deux séances par jour. Le plus dur, c'est la récupération : dormir neuf heures et bien manger.",
    audioEn: "Journalist: How do you prepare for the Games? — Athlete: I train six days out of seven, two sessions daily. Hardest is recovery: nine hours sleep and good food.",
    q: "Selon lui, le plus dur ?", qEn: "According to them, the hardest part?",
    choices: ["La récupération (sommeil, alimentation)", "Trouver un coach", "Payer l'équipement", "Voyager"],
    choicesEn: ["Recovery (sleep, food)", "Finding a coach", "Paying for gear", "Travelling"],
    answer: 0, explain: "Le plus dur, c'est... = opinion marker.", explainFr: "Le plus dur, c'est... = marqueur d'opinion." },
  { n: 27, section: "F", group: "IV3", topic: "Interview – author",
    audio: "Journaliste : D'où vient l'idée de votre roman ? — Autrice : D'une lettre de mon grand-père, trouvée dans un grenier. J'ai mis trois ans à transformer cette histoire vraie en fiction.",
    audioEn: "Journalist: Where did your novel's idea come from? — Author: From my grandfather's letter, found in an attic. It took three years to turn this true story into fiction.",
    q: "D'où vient l'idée ?", qEn: "Where did the idea come from?",
    choices: ["D'une lettre de son grand-père", "D'un rêve", "D'un voyage en Asie", "D'un film"],
    choicesEn: ["Grandfather's letter", "A dream", "An Asia trip", "A film"],
    answer: 0, explain: "D'une lettre... trouvée dans un grenier.", explainFr: "D'une lettre... trouvée dans un grenier." },
  { n: 28, section: "F", group: "IV3", topic: "Interview – author",
    audio: "Journaliste : D'où vient l'idée de votre roman ? — Autrice : D'une lettre de mon grand-père, trouvée dans un grenier. J'ai mis trois ans à transformer cette histoire vraie en fiction.",
    audioEn: "Journalist: Where did your novel's idea come from? — Author: From my grandfather's letter, found in an attic. It took three years to turn this true story into fiction.",
    q: "Combien de temps d'écriture ?", qEn: "How long to write?",
    choices: ["Trois ans", "Trois mois", "Dix ans", "Une semaine"],
    choicesEn: ["Three years", "Three months", "Ten years", "One week"],
    answer: 0, explain: "Trois ans — number trap avoided by listening fully.", explainFr: "Trois ans — piège de nombres évité en écoutant tout." },
  { n: 29, section: "F", group: "IV4", topic: "Interview – founder",
    audio: "Journaliste : Votre application aide les nouveaux arrivants ? — Fondatrice : Oui, elle traduit les documents administratifs en dix langues. Nous avons déjà cent mille utilisateurs, dont soixante mille au Canada.",
    audioEn: "Journalist: Your app helps newcomers? — Founder: Yes, it translates administrative documents into ten languages. We already have 100k users, 60k in Canada.",
    q: "Que fait l'application ?", qEn: "What does the app do?",
    choices: ["Traduit les documents administratifs", "Vend des billets d'avion", "Donne des cours de cuisine", "Loue des appartements"],
    choicesEn: ["Translates admin documents", "Sells plane tickets", "Gives cooking classes", "Rents apartments"],
    answer: 0, explain: "Traduit les documents administratifs en dix langues.", explainFr: "Traduit les documents administratifs en dix langues." },
  { n: 30, section: "F", group: "IV4", topic: "Interview – founder",
    audio: "Journaliste : Votre application aide les nouveaux arrivants ? — Fondatrice : Oui, elle traduit les documents administratifs en dix langues. Nous avons déjà cent mille utilisateurs, dont soixante mille au Canada.",
    audioEn: "Journalist: Your app helps newcomers? — Founder: Yes, it translates administrative documents into ten languages. We already have 100k users, 60k in Canada.",
    q: "Combien d'utilisateurs au Canada ?", qEn: "How many users in Canada?",
    choices: ["Soixante mille", "Cent mille", "Dix mille", "Dix langues"],
    choicesEn: ["Sixty thousand", "One hundred thousand", "Ten thousand", "Ten languages"],
    answer: 0, explain: "Dont soixante mille au Canada. Trap: 100k = total.", explainFr: "Dont soixante mille au Canada. Piège : 100k = total." },

  // ---- G Q31-40 report + documents ----
  { n: 31, section: "G", group: "REP", topic: "Reportage / Report",
    audio: "Reportage : À Lyon, l'ancienne usine Berliet devient un éco-quartier : huit cents logements, une école et un parc de trois hectares. Les travaux dureront quatre ans et coûteront deux cents millions d'euros.",
    audioEn: "Report: In Lyon, the old Berliet factory becomes an eco-district: 800 homes, a school, a 3-hectare park. Works last four years, cost 200 million euros.",
    q: "Que prévoit le projet ?", qEn: "What does the project include?",
    choices: ["800 logements, école, parc de 3 ha", "Un stade et un aéroport", "Une autoroute", "Rien, projet annulé"],
    choicesEn: ["800 homes, school, 3-ha park", "A stadium and airport", "A highway", "Nothing, cancelled"],
    answer: 0, explain: "Three elements listed: logements, école, parc.", explainFr: "Trois éléments : logements, école, parc." },
  { n: 32, section: "G", group: "REP", topic: "Reportage / Report",
    audio: "Reportage : À Lyon, l'ancienne usine Berliet devient un éco-quartier : huit cents logements, une école et un parc de trois hectares. Les travaux dureront quatre ans et coûteront deux cents millions d'euros.",
    audioEn: "Report: In Lyon, the old Berliet factory becomes an eco-district: 800 homes, a school, a 3-hectare park. Works last four years, cost 200 million euros.",
    q: "Durée et coût des travaux ?", qEn: "Duration and cost?",
    choices: ["4 ans, 200 millions d'euros", "3 ans, 800 millions", "8 ans, 4 millions", "1 an, gratuit"],
    choicesEn: ["4 years, €200M", "3 years, €800M", "8 years, €4M", "1 year, free"],
    answer: 0, explain: "Quatre ans + deux cents millions. Other numbers belong elsewhere.", explainFr: "Quatre ans + deux cents millions. Les autres nombres sont ailleurs." },
  { n: 33, section: "G", group: "REP", topic: "Reportage / Report",
    audio: "Reportage : À Lyon, l'ancienne usine Berliet devient un éco-quartier : huit cents logements, une école et un parc de trois hectares. Les travaux dureront quatre ans et coûteront deux cents millions d'euros.",
    audioEn: "Report: In Lyon, the old Berliet factory becomes an eco-district: 800 homes, a school, a 3-hectare park. Works last four years, cost 200 million euros.",
    q: "Quel site est transformé ?", qEn: "Which site is converted?",
    choices: ["L'ancienne usine Berliet à Lyon", "La gare de Lyon", "Un château", "Un port"],
    choicesEn: ["The old Berliet factory in Lyon", "Lyon station", "A castle", "A port"],
    answer: 0, explain: "Given in the opening clause.", explainFr: "Donné dans la 1re phrase." },
  { n: 34, section: "G", topic: "Document – health",
    audio: "Pharmacie centrale : garde de nuit ce week-end, samedi et dimanche, de vingt heures à huit heures. Ordonnance obligatoire pour les antibiotiques.",
    audioEn: "Central pharmacy: night duty this weekend, Saturday and Sunday 8pm–8am. Prescription required for antibiotics.",
    q: "Quand la pharmacie de garde est-elle ouverte ?", qEn: "When is the duty pharmacy open?",
    choices: ["Samedi et dimanche 20h–8h", "En semaine 9h–18h", "Uniquement le lundi", "24h/24 toute l'année"],
    choicesEn: ["Sat–Sun 8pm–8am", "Weekdays 9–6", "Mondays only", "24/7 all year"],
    answer: 0, explain: "Garde de nuit ce week-end + hours.", explainFr: "Garde de nuit ce week-end + horaires." },
  { n: 35, section: "G", topic: "Document – school",
    audio: "Inscriptions au club de tennis : mercredi de quatorze à dix-sept heures au gymnase. Certificat médical de moins de trois mois exigé. Tarif : quatre-vingts euros l'année.",
    audioEn: "Tennis club registration: Wednesday 2–5pm at the gym. Medical certificate under three months required. Fee: eighty euros a year.",
    q: "Que faut-il pour s'inscrire ?", qEn: "What is needed to register?",
    choices: ["Certificat médical récent + 80 €", "Juste une photo", "Avoir 18 ans", "Un essai gratuit"],
    choicesEn: ["Recent medical certificate + €80", "Just a photo", "Be 18", "A free trial"],
    answer: 0, explain: "Deux conditions : certificat + tarif.", explainFr: "Deux conditions : certificat + tarif." },
  { n: 36, section: "G", topic: "Document – bank",
    audio: "Votre agence sera exceptionnellement fermée lundi toute la journée pour travaux. Vos opérations restent possibles en ligne ou au distributeur.",
    audioEn: "Your branch will be exceptionally closed all day Monday for works. Use online banking or the ATM.",
    q: "Que faire lundi ?", qEn: "What to do Monday?",
    choices: ["Utiliser la banque en ligne ou le distributeur", "Venir à l'agence", "Appeler la police", "Attendre un mois"],
    choicesEn: ["Use online banking or ATM", "Come to the branch", "Call police", "Wait a month"],
    answer: 0, explain: "Fermée lundi → alternatives given.", explainFr: "Fermée lundi → alternatives données." },
  { n: 37, section: "G", topic: "Document – job",
    audio: "Offre d'emploi : serveur ou serveuse, week-end uniquement, expérience d'un an exigée. Envoyez CV et lettre avant le trente du mois.",
    audioEn: "Job: waiter/waitress, weekends only, one year experience required. Send CV + letter before the 30th.",
    q: "Profil demandé ?", qEn: "Required profile?",
    choices: ["1 an d'expérience, dispo week-end", "Sans expérience, semaine", "Cuisinier confirmé", "Bénévole"],
    choicesEn: ["1 yr experience, weekends free", "No experience, weekdays", "Experienced cook", "Volunteer"],
    answer: 0, explain: "Week-end uniquement + un an exigée + deadline 30.", explainFr: "Week-end uniquement + un an exigée + limite le 30." },
  { n: 38, section: "G", topic: "Document – transport",
    audio: "Abonnement mensuel : soixante-quinze euros, valable sur tout le réseau bus et métro. Les étudiants de moins de vingt-six ans paient moitié prix.",
    audioEn: "Monthly pass: seventy-five euros, valid bus + metro. Students under 26 pay half price.",
    q: "Combien paie un étudiant de 20 ans ?", qEn: "How much for a 20-year-old student?",
    choices: ["Moitié prix (37,50 €)", "75 €", "Gratuit", "26 €"],
    choicesEn: ["Half price (€37.50)", "€75", "Free", "€26"],
    answer: 0, explain: "Moins de 26 ans → moitié prix. Compute: 75/2.", explainFr: "Moins de 26 ans → moitié prix. Calcul : 75/2." },
  { n: 39, section: "G", topic: "Document – housing",
    audio: "Studio meublé, trente mètres carrés, proche université. Loyer : six cent cinquante euros, charges non comprises. Libre le premier avril.",
    audioEn: "Furnished studio, 30 m², near university. Rent €650 excluding charges. Free April 1st.",
    q: "Quel loyer total le 1er mois (charges 50 €) ?", qEn: "Total first-month rent (charges €50)?",
    choices: ["700 €", "650 €", "600 €", "50 €"],
    choicesEn: ["€700", "€650", "€600", "€50"],
    answer: 0, explain: "Charges non comprises → add: 650+50.", explainFr: "Charges non comprises → addition : 650+50." },
  { n: 40, section: "G", topic: "Document – culture",
    audio: "Exposition « Lumières du Nord » : du dix mars au trente juin, tous les jours sauf le lundi, de dix heures à dix-huit heures. Entrée : douze euros, gratuit moins de douze ans.",
    audioEn: "Exhibition 'Northern Lights': March 10–June 30, daily except Monday, 10am–6pm. Entry €12, free under 12.",
    q: "Quand peut-on visiter ?", qEn: "When can you visit?",
    choices: ["Tous les jours sauf lundi, 10h–18h", "Uniquement le lundi", "La nuit", "En janvier"],
    choicesEn: ["Daily except Monday 10–6", "Mondays only", "Nights", "January"],
    answer: 0, explain: "Tous les jours sauf le lundi + hours.", explainFr: "Tous les jours sauf le lundi + horaires." },
];

export const readingSections = [
  { id: "A", range: "Q1–7", en: "Short documents: find the main intent", fr: "Documents courts : intention principale" },
  { id: "B", range: "Q8–17", en: "Fill-in-the-blank vocab & grammar", fr: "Compléter : vocabulaire et grammaire" },
  { id: "C", range: "Q18–40", en: "Deep reading: long paragraphs, harder as you go", fr: "Lecture approfondie : longs paragraphes, difficulté croissante" },
];

export const readingItems = [
  // ---- A Q1-7 document matching (4 docs, pick matching one) ----
  { n: 1, section: "A", type: "match", title: "Leisure / Loisirs", titleFr: "Loisirs", level: "A2",
    docs: ["A – Piscine : fermée lundi pour vidange.", "B – Cinéma : séance à 20h30, tarif réduit étudiants.", "C – Bibliothèque : ouverte samedi 10h–17h.", "D – Stade : match dimanche, entrée gratuite."],
    docsEn: ["A – Pool: closed Monday for draining.", "B – Cinema: 8:30pm show, student discount.", "C – Library: open Saturday 10–5.", "D – Stadium: Sunday match, free entry."],
    q: "Léa, étudiante, veut sortir samedi soir pas cher. Quel document l'aide ?", qEn: "Léa, a student, wants a cheap Saturday night out. Which document helps?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 1, explain: "Samedi soir + pas cher + étudiante → cinéma tarif réduit.", explainFr: "Samedi soir + pas cher + étudiante → cinéma tarif réduit." },
  { n: 2, section: "A", type: "match", title: "Health / Santé", titleFr: "Santé", level: "A2",
    docs: ["A – Dentiste : urgences le matin sans rendez-vous.", "B – Pharmacie : garde dimanche 9h–13h.", "C – Hôpital : visites 14h–20h.", "D – Laboratoire : résultats en 48h."],
    docsEn: ["A – Dentist: morning emergencies, no appointment.", "B – Pharmacy: Sunday duty 9–1.", "C – Hospital: visits 2–8pm.", "D – Lab: results in 48h."],
    q: "Karim a mal aux dents dimanche matin. Quel document ?", qEn: "Karim has toothache Sunday morning. Which document?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 0, explain: "Mal aux dents + urgences sans rendez-vous → dentiste.", explainFr: "Mal aux dents + urgences sans rendez-vous → dentiste." },
  { n: 3, section: "A", type: "match", title: "Transport", titleFr: "Transport", level: "A2",
    docs: ["A – Bus 12 : dévié par la rue des Fleurs.", "B – Métro : ticket SMS au 06 12 34 56.", "C – Train : guichet fermé, billets en ligne.", "D – Vélo : station hors service place du Marché."],
    docsEn: ["A – Bus 12: diverted via Rue des Fleurs.", "B – Metro: SMS ticket.", "C – Train: counter closed, tickets online.", "D – Bike station out of service."],
    q: "Mei veut acheter son billet de train. Quel document ?", qEn: "Mei wants to buy a train ticket. Which document?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 2, explain: "Billet de train + guichet fermé → en ligne.", explainFr: "Billet de train + guichet fermé → en ligne." },
  { n: 4, section: "A", type: "match", title: "Housing / Logement", titleFr: "Logement", level: "B1",
    docs: ["A – Agence : visites sur rendez-vous uniquement.", "B – Gardienne : colis au local A, code 4582.", "C – Ascenseur : en panne jusqu'à vendredi.", "D – Parking : places visiteurs au -1."],
    docsEn: ["A – Agency: viewings by appointment only.", "B – Caretaker: parcels in room A, code 4582.", "C – Elevator out until Friday.", "D – Parking: visitor spots level -1."],
    q: "Où Yan doit-il chercher son colis ?", qEn: "Where should Yan look for his parcel?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 1, explain: "Colis → gardienne, local A.", explainFr: "Colis → gardienne, local A." },
  { n: 5, section: "A", type: "match", title: "Work / Travail", titleFr: "Travail", level: "B1",
    docs: ["A – Cantine fermée jeudi, panier-repas 11h30–13h.", "B – Réunion avancée à 14h, salle B.", "C – Télétravail : demande avant le 15.", "D – Parking : badge obligatoire dès lundi."],
    docsEn: ["A – Canteen closed Thursday, packed lunch.", "B – Meeting moved to 2pm, room B.", "C – Remote work: apply before the 15th.", "D – Parking: badge required from Monday."],
    q: "Nadia veut télétravailler. Quel document ?", qEn: "Nadia wants remote work. Which document?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 2, explain: "Télétravail → demande avant le 15.", explainFr: "Télétravail → demande avant le 15." },
  { n: 6, section: "A", type: "match", title: "Studies / Études", titleFr: "Études", level: "B1",
    docs: ["A – Bourses : dossier avant le 30 avril.", "B – Examens : convocation par mail.", "C – Bibliothèque : nocturne jeudi jusqu'à 22h.", "D – Sport : inscription au gymnase."],
    docsEn: ["A – Grants: file before April 30.", "B – Exams: summons by email.", "C – Library: Thursday late opening till 10pm.", "D – Sports: register at the gym."],
    q: "Paul veut réviser tard jeudi. Quel document ?", qEn: "Paul wants to study late Thursday. Which document?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 2, explain: "Réviser tard jeudi → nocturne bibliothèque.", explainFr: "Réviser tard jeudi → nocturne bibliothèque." },
  { n: 7, section: "A", type: "match", title: "Travel / Voyage", titleFr: "Voyage", level: "B1",
    docs: ["A – Passeport : délai de 3 semaines.", "B – Hôtel : annulation gratuite 48h avant.", "C – Vol : enregistrement en ligne dès 30h avant.", "D – Visa : photo d'identité récente exigée."],
    docsEn: ["A – Passport: 3-week delay.", "B – Hotel: free cancellation 48h before.", "C – Flight: online check-in from 30h before.", "D – Visa: recent ID photo required."],
    q: "Sara doit refaire sa photo de visa. Quel document ?", qEn: "Sara must redo her visa photo. Which document?",
    choices: ["Document A", "Document B", "Document C", "Document D"], choicesEn: ["Document A", "Document B", "Document C", "Document D"],
    answer: 3, explain: "Photo d'identité récente → visa.", explainFr: "Photo d'identité récente → visa." },

  // ---- B Q8-17 completion ----
  { n: 8, section: "B", type: "fib", title: "Email", titleFr: "Courriel", level: "B1",
    text: "Merci de confirmer votre présence ___ vendredi 18h ___ envoyant un message avant mercredi soir.",
    textEn: "Please confirm attendance ___ Friday 6pm ___ sending a message before Wednesday. (avant / en)",
    q: "Complétez : ___ / ___", qEn: "Fill in the two words.", choices: [], choicesEn: [], fib: ["avant", "en"],
    explain: "Avant + time; en + gerund (envoyant).", explainFr: "Avant + heure ; en + gérondif." },
  { n: 9, section: "B", type: "fib", title: "Health", titleFr: "Santé", level: "B1",
    text: "Il est recommandé de boire ___ moins un litre et demi d'eau ___ jour, surtout en été.",
    textEn: "Drink ___ least 1.5L of water ___ day, especially in summer. (au / par)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["au", "par"],
    explain: "Au moins + par jour: fixed phrases.", explainFr: "Au moins + par jour : locutions figées." },
  { n: 10, section: "B", type: "fib", title: "Work", titleFr: "Travail", level: "B1",
    text: "La réunion aura lieu ___ matin à neuf heures ___ la salle de conférence.",
    textEn: "The meeting is ___ morning at nine ___ the conference room. (le / dans)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["le", "dans"],
    explain: "Le matin (habit/datetime); dans la salle (place).", explainFr: "Le matin ; dans la salle (lieu)." },
  { n: 11, section: "B", type: "fib", title: "Travel", titleFr: "Voyage", level: "B1",
    text: "Nous sommes partis ___ gare à sept heures et arrivés ___ Montréal à midi.",
    textEn: "We left ___ station at seven and arrived ___ Montreal at noon. (de la / à)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["de la", "à"],
    answer: 0, choices: undefined, choicesEn: undefined,
    explain: "Partir de + arriver à (city).", explainFr: "Partir de + arriver à (ville)." },
  { n: 12, section: "B", type: "fib", title: "Studies", titleFr: "Études", level: "B2",
    text: "___ que les résultats soient publiés, les étudiants doivent garder leur convocation.",
    textEn: "___ the results are published, students must keep their summons. (En attendant)",
    q: "Complétez (2 mots)", qEn: "Fill in (2 words).", choices: [], choicesEn: [], fib: ["en", "attendant"],
    explain: "En attendant que = while waiting for.", explainFr: "En attendant que = en attendant la publication." },
  { n: 13, section: "B", type: "fib", title: "Housing", titleFr: "Logement", level: "B2",
    text: "L'appartement se trouve ___ cinq minutes ___ pied de la station de métro.",
    textEn: "The apartment is ___ five minutes ___ foot from the metro. (à / à)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["à", "à"],
    explain: "À cinq minutes à pied: fixed phrase.", explainFr: "À cinq minutes à pied : locution." },
  { n: 14, section: "B", type: "fib", title: "Opinion", titleFr: "Opinion", level: "B2",
    text: "___ mon avis, il est essentiel ___ limiter les écrans chez les enfants.",
    textEn: "___ my opinion, it is essential ___ limit children's screens. (À / de)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["à", "de"],
    explain: "À mon avis; essentiel de + infinitive.", explainFr: "À mon avis ; essentiel de + infinitif." },
  { n: 15, section: "B", type: "fib", title: "News", titleFr: "Actualités", level: "B2",
    text: "Le festival aura lieu ___ plein air, ___ cas de pluie les concerts seront déplacés.",
    textEn: "The festival is outdoors; ___ rain the concerts move inside. (en / en)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["en", "en"],
    explain: "En plein air; en cas de = in case of.", explainFr: "En plein air ; en cas de." },
  { n: 16, section: "B", type: "fib", title: "Services", titleFr: "Services", level: "B2",
    text: "Pour bénéficier ___ la remise, présentez ce coupon ___ caisse.",
    textEn: "To get ___ discount, show this coupon ___ checkout. (de / en)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["de", "en"],
    explain: "Bénéficier de; en caisse.", explainFr: "Bénéficier de ; en caisse." },
  { n: 17, section: "B", type: "fib", title: "Environment", titleFr: "Environnement", level: "B2",
    text: "___ à cette loi, la qualité de l'air s'est améliorée ___ les grandes villes.",
    textEn: "___ this law, air quality improved ___ big cities. (Grâce / dans)",
    q: "Complétez", qEn: "Fill in.", choices: [], choicesEn: [], fib: ["grâce", "dans"],
    explain: "Grâce à (positive cause); dans les villes.", explainFr: "Grâce à (cause positive) ; dans les villes." },

  // ---- C Q18-21 short-text series ----
  { n: 18, section: "C", type: "series", title: "Lost and found", titleFr: "Objets trouvés", level: "B1",
    docs: ["A – Trouvé : clés avec porte-clés rouge, tram B.", "B – Perdu : portefeuille noir, gare, samedi.", "C – Trouvé : écharpe bleue, bibliothèque.", "D – Perdu : lunettes, cinéma, rangée 5."],
    docsEn: ["A – Found: keys, red keyring, tram B.", "B – Lost: black wallet, station, Saturday.", "C – Found: blue scarf, library.", "D – Lost: glasses, cinema, row 5."],
    q: "Nadia a perdu son portefeuille samedi à la gare. Quelle annonce correspond ?", qEn: "Nadia lost her wallet Saturday at the station. Which notice?",
    choices: ["Annonce A", "Annonce B", "Annonce C", "Annonce D"], choicesEn: ["Notice A", "Notice B", "Notice C", "Notice D"],
    answer: 1, explain: "Portefeuille + gare + samedi = B.", explainFr: "Portefeuille + gare + samedi = B." },
  { n: 19, section: "C", type: "series", title: "Job ads", titleFr: "Offres d'emploi", level: "B1",
    docs: ["A – Serveuse, soir uniquement, dès 18 ans.", "B – Livreur vélo, week-end, permis non exigé.", "C – Caissier, temps plein, expérience exigée.", "D – Baby-sitter, mercredis, références demandées."],
    docsEn: ["A – Waitress, evenings, 18+.", "B – Bike courier, weekends.", "C – Cashier, full-time, experience.", "D – Babysitter, Wednesdays."],
    q: "Léo, 17 ans, cherche un job le week-end sans permis. Quelle offre ?", qEn: "Léo, 17, wants weekend work, no licence. Which offer?",
    choices: ["Offre A", "Offre B", "Offre C", "Offre D"], choicesEn: ["Offer A", "Offer B", "Offer C", "Offer D"],
    answer: 1, explain: "Week-end + sans permis + 17 ans → livreur vélo.", explainFr: "Week-end + sans permis + 17 ans → livreur vélo." },
  { n: 20, section: "C", type: "series", title: "Courses", titleFr: "Cours", level: "B2",
    docs: ["A – Cuisine italienne, lundi 19h, 120 €.", "B – Français B2, mardi et jeudi 18h, 200 €.", "C – Yoga, samedi 9h, 60 €.", "D – Photo, mercredi 20h, 90 €."],
    docsEn: ["A – Italian cooking Mon 7pm €120.", "B – French B2 Tue+Thu 6pm €200.", "C – Yoga Sat 9am €60.", "D – Photo Wed 8pm €90."],
    q: "Inès veut un cours de français B2 le soir en semaine. Lequel ?", qEn: "Inès wants evening weekday B2 French. Which?",
    choices: ["Cours A", "Cours B", "Cours C", "Cours D"], choicesEn: ["Course A", "Course B", "Course C", "Course D"],
    answer: 1, explain: "Français B2 + mardi/jeudi 18h.", explainFr: "Français B2 + mardi/jeudi 18h." },
  { n: 21, section: "C", type: "series", title: "Housing ads", titleFr: "Annonces logement", level: "B2",
    docs: ["A – Studio 25 m², 700 €, charges comprises.", "B – T2 45 m², 950 €, + parking 50 €.", "C – Chambre chez l'habitant, 400 €.", "D – T3 65 m², 1200 €, proche métro."],
    docsEn: ["A – Studio 25m² €700 incl.", "B – 1-bed 45m² €950 + €50 parking.", "C – Room in house €400.", "D – 2-bed 65m² €1200 near metro."],
    q: "Budget max 750 € charges comprises. Quelle annonce ?", qEn: "Max budget €750 including charges. Which ad?",
    choices: ["Annonce A", "Annonce B", "Annonce C", "Annonce D"], choicesEn: ["Ad A", "Ad B", "Ad C", "Ad D"],
    answer: 0, explain: "Seule A respecte 750 charges comprises.", explainFr: "Seule A respecte 750 charges comprises." },

  // ---- D Q22-23 graphs ----
  { n: 22, section: "D", type: "graph", title: "Survey / Sondage", titleFr: "Sondage", level: "B2",
    text: "Sondage « transports » (1000 personnes) : vélo 15 %, bus 25 %, métro 35 %, voiture 20 %, marche 5 %.",
    textEn: "Transport survey (1000 people): bike 15%, bus 25%, metro 35%, car 20%, walking 5%.",
    q: "Quelle affirmation est correcte ?", qEn: "Which statement is correct?",
    choices: ["Le métro est le transport le plus utilisé", "La voiture dépasse le métro", "La marche dépasse le vélo", "Le bus est dernier"],
    choicesEn: ["Metro is the most used", "Car beats metro", "Walking beats biking", "Bus is last"],
    answer: 0, explain: "35 % = max. Compare all figures.", explainFr: "35 % = max. Compare tous les chiffres." },
  { n: 23, section: "D", type: "graph", title: "Results / Résultats", titleFr: "Résultats", level: "B2",
    text: "Réussite à l'examen : 2021 : 60 %, 2022 : 65 %, 2023 : 64 %, 2024 : 72 %.",
    textEn: "Exam pass rates: 2021: 60%, 2022: 65%, 2023: 64%, 2024: 72%.",
    q: "Que montre le graphique ?", qEn: "What does the graph show?",
    choices: ["Hausse globale avec un léger recul en 2023", "Baisse continue", "Stabilité parfaite", "Aucune donnée 2024"],
    choicesEn: ["Overall rise with a slight 2023 dip", "Steady fall", "Perfect stability", "No 2024 data"],
    answer: 0, explain: "60→65→64→72: up overall, small 2023 dip.", explainFr: "60→65→64→72 : hausse globale, creux 2023." },

  // ---- E Q24-31 admin docs (4 docs x 2 Qs) ----
  { n: 24, section: "E", type: "mcq", doc: "ADM1", title: "University / Université", titleFr: "Université", level: "B2",
    text: "Inscription définitive validée après réception du dossier complet, y compris un certificat médical de moins de trois mois. Frais : 300 € avant le 15 septembre, 350 € après.",
    textEn: "Final registration validated after complete file received, including a medical certificate under three months old. Fees: €300 before Sept 15, €350 after.",
    q: "Condition de validation ?", qEn: "Validation requirement?",
    choices: ["Dossier complet + certificat récent", "Payer en ligne", "Venir avec un parent", "Parler anglais"],
    choicesEn: ["Complete file + recent certificate", "Pay online", "Come with a parent", "Speak English"],
    answer: 0, explain: "Ne... que après = strict condition.", explainFr: "Ne... que après = condition stricte." },
  { n: 25, section: "E", type: "mcq", doc: "ADM1", title: "University / Université", titleFr: "Université", level: "B2",
    text: "Inscription définitive validée après réception du dossier complet, y compris un certificat médical de moins de trois mois. Frais : 300 € avant le 15 septembre, 350 € après.",
    textEn: "Final registration validated after complete file received, including a medical certificate under three months old. Fees: €300 before Sept 15, €350 after.",
    q: "Frais payés le 20 septembre ?", qEn: "Fees paid September 20?",
    choices: ["350 €", "300 €", "Gratuit", "250 €"],
    choicesEn: ["€350", "€300", "Free", "€250"],
    answer: 0, explain: "Après le 15 septembre → 350 €.", explainFr: "Après le 15 septembre → 350 €." },
  { n: 26, section: "E", type: "mcq", doc: "ADM2", title: "Town hall / Mairie", titleFr: "Mairie", level: "B2",
    text: "Passeport : dépôt du dossier en mairie sur rendez-vous. Délai moyen : trois semaines. Pièces : acte de naissance, photo récente, justificatif de domicile de moins d'un an.",
    textEn: "Passport: file at town hall by appointment. Average delay: three weeks. Documents: birth certificate, recent photo, proof of address under one year old.",
    q: "Quel délai moyen ?", qEn: "Average delay?",
    choices: ["Trois semaines", "Trois jours", "Trois mois", "Un an"],
    choicesEn: ["Three weeks", "Three days", "Three months", "One year"],
    answer: 0, explain: "Délai moyen : trois semaines.", explainFr: "Délai moyen : trois semaines." },
  { n: 27, section: "E", type: "mcq", doc: "ADM2", title: "Town hall / Mairie", titleFr: "Mairie", level: "B2",
    text: "Passeport : dépôt du dossier en mairie sur rendez-vous. Délai moyen : trois semaines. Pièces : acte de naissance, photo récente, justificatif de domicile de moins d'un an.",
    textEn: "Passport: file at town hall by appointment. Average delay: three weeks. Documents: birth certificate, recent photo, proof of address under one year old.",
    q: "Justificatif accepté ?", qEn: "Accepted proof?",
    choices: ["De moins d'un an", "De plus de cinq ans", "Aucun", "Seulement le passeport"],
    choicesEn: ["Under one year old", "Over five years old", "None", "Passport only"],
    answer: 0, explain: "De moins d'un an.", explainFr: "De moins d'un an." },
  { n: 28, section: "E", type: "mcq", doc: "ADM3", title: "Bank / Banque", titleFr: "Banque", level: "B2",
    text: "Ouverture de compte : pièce d'identité + justificatif de domicile. Les étudiants bénéficient de la gratuité la première année, puis 5 € par mois.",
    textEn: "Account opening: ID + proof of address. Students get the first year free, then €5/month.",
    q: "Avantage étudiant ?", qEn: "Student benefit?",
    choices: ["Gratuité la 1re année", "Compte à 50 €/mois", "Aucun avantage", "Carte payante aussitôt"],
    choicesEn: ["Free first year", "€50/month account", "No benefit", "Paid card immediately"],
    answer: 0, explain: "Gratuité la première année, puis 5 €.", explainFr: "Gratuité la première année, puis 5 €." },
  { n: 29, section: "E", type: "mcq", doc: "ADM3", title: "Bank / Banque", titleFr: "Banque", level: "B2",
    text: "Ouverture de compte : pièce d'identité + justificatif de domicile. Les étudiants bénéficient de la gratuité la première année, puis 5 € par mois.",
    textEn: "Account opening: ID + proof of address. Students get the first year free, then €5/month.",
    q: "Documents exigés ?", qEn: "Required documents?",
    choices: ["ID + justificatif de domicile", "Seulement le passeport", "Rien", "Fiche de paie uniquement"],
    choicesEn: ["ID + proof of address", "Passport only", "Nothing", "Payslip only"],
    answer: 0, explain: "Pièce d'identité + justificatif.", explainFr: "Pièce d'identité + justificatif." },
  { n: 30, section: "E", type: "mcq", doc: "ADM4", title: "Insurance / Assurance", titleFr: "Assurance", level: "B2",
    text: "Déclarez tout sinistre dans les cinq jours ouvrés. Passé ce délai, la garantie peut être refusée, sauf cas de force majeure dûment justifié.",
    textEn: "Declare any claim within five working days. After that, coverage may be refused, except duly justified force majeure.",
    q: "Délai de déclaration ?", qEn: "Declaration deadline?",
    choices: ["5 jours ouvrés", "5 mois", "1 an", "Aucun délai"],
    choicesEn: ["5 working days", "5 months", "1 year", "No deadline"],
    answer: 0, explain: "Cinq jours ouvrés.", explainFr: "Cinq jours ouvrés." },
  { n: 31, section: "E", type: "mcq", doc: "ADM4", title: "Insurance / Assurance", titleFr: "Assurance", level: "B2",
    text: "Déclarez tout sinistre dans les cinq jours ouvrés. Passé ce délai, la garantie peut être refusée, sauf cas de force majeure dûment justifié.",
    textEn: "Declare any claim within five working days. After that, coverage may be refused, except duly justified force majeure.",
    q: "Si déclaration tardive ?", qEn: "If declared late?",
    choices: ["Garantie refusée sauf force majeure", "Doublement du remboursement", "Rien ne change", "Bonus offert"],
    choicesEn: ["Coverage refused except force majeure", "Double refund", "No change", "Bonus offered"],
    answer: 0, explain: "Passé ce délai → refusée, sauf exception.", explainFr: "Passé ce délai → refusée, sauf exception." },

  // ---- F Q32-40 press articles (4 articles: 2+2+2+3 Qs) ----
  { n: 32, section: "F", type: "mcq", doc: "PR1", title: "Remote work / Télétravail", titleFr: "Télétravail", level: "B2",
    text: "Le télétravail séduit de plus en plus de salariés. Pourtant, certains managers s'inquiètent d'une baisse de la cohésion d'équipe, tandis que d'autres y voient un levier de productivité.",
    textEn: "Remote work attracts more employees. Yet some managers fear weaker team cohesion, while others see a productivity lever.",
    q: "Idée principale ?", qEn: "Main idea?",
    choices: ["Avis partagés", "Unanimité pour", "Rejet total", "Interdiction prochaine"],
    choicesEn: ["Mixed opinions", "Unanimous support", "Total rejection", "Upcoming ban"],
    answer: 0, explain: "Pourtant / tandis que = contrast.", explainFr: "Pourtant / tandis que = opposition." },
  { n: 33, section: "F", type: "mcq", doc: "PR1", title: "Remote work / Télétravail", titleFr: "Télétravail", level: "B2",
    text: "Le télétravail séduit de plus en plus de salariés. Pourtant, certains managers s'inquiètent d'une baisse de la cohésion d'équipe, tandis que d'autres y voient un levier de productivité.",
    textEn: "Remote work attracts more employees. Yet some managers fear weaker team cohesion, while others see a productivity lever.",
    q: "Que craignent certains managers ?", qEn: "What do some managers fear?",
    choices: ["Une baisse de la cohésion", "Une hausse des salaires", "Trop de vacances", "Le bruit"],
    choicesEn: ["Weaker cohesion", "Higher wages", "Too much holiday", "Noise"],
    answer: 0, explain: "Baisse de la cohésion d'équipe.", explainFr: "Baisse de la cohésion d'équipe." },
  { n: 34, section: "F", type: "mcq", doc: "PR2", title: "Screens / Écrans", titleFr: "Écrans", level: "B2",
    text: "Bien que les écrans fassent partie du quotidien, il est crucial d'en limiter l'usage chez les plus jeunes, car l'excès nuit à la concentration.",
    textEn: "Although screens are daily life, limiting use among the youngest is crucial, because excess harms concentration.",
    q: "Position de l'auteur ?", qEn: "Author's position?",
    choices: ["Limiter chez les jeunes", "Écrans sans limite", "Contre toute technologie", "Neutre"],
    choicesEn: ["Limit among the young", "Unlimited screens", "Against all tech", "Neutral"],
    answer: 0, explain: "Bien que + subjonctif; car = cause.", explainFr: "Bien que + subjonctif ; car = cause." },
  { n: 35, section: "F", type: "mcq", doc: "PR2", title: "Screens / Écrans", titleFr: "Écrans", level: "B2",
    text: "Bien que les écrans fassent partie du quotidien, il est crucial d'en limiter l'usage chez les plus jeunes, car l'excès nuit à la concentration.",
    textEn: "Although screens are daily life, limiting use among the youngest is crucial, because excess harms concentration.",
    q: "Pourquoi limiter ?", qEn: "Why limit?",
    choices: ["L'excès nuit à la concentration", "Les écrans sont chers", "Les parents l'exigent", "La loi l'interdit"],
    choicesEn: ["Excess harms concentration", "Screens are expensive", "Parents demand it", "Law forbids it"],
    answer: 0, explain: "Car l'excès nuit à la concentration.", explainFr: "Car l'excès nuit à la concentration." },
  { n: 36, section: "F", type: "mcq", doc: "PR3", title: "City / Ville", titleFr: "Ville", level: "B2",
    text: "Depuis 2020, la ville a créé douze kilomètres de pistes cyclables. Les accidents impliquant des vélos ont chuté de vingt pour cent, mais les commerçants du centre se plaignent de la suppression de deux cents places de parking.",
    textEn: "Since 2020, the city built 12 km of bike lanes. Bike accidents fell 20%, but downtown shops complain about 200 removed parking spots.",
    q: "Effet positif ?", qEn: "Positive effect?",
    choices: ["Accidents vélo -20 %", "Plus de parkings", "Moins de vélos", "Hausse des prix"],
    choicesEn: ["Bike accidents -20%", "More parking", "Fewer bikes", "Higher prices"],
    answer: 0, explain: "Chuté de vingt pour cent.", explainFr: "Chuté de vingt pour cent." },
  { n: 37, section: "F", type: "mcq", doc: "PR3", title: "City / Ville", titleFr: "Ville", level: "B2",
    text: "Depuis 2020, la ville a créé douze kilomètres de pistes cyclables. Les accidents impliquant des vélos ont chuté de vingt pour cent, mais les commerçants du centre se plaignent de la suppression de deux cents places de parking.",
    textEn: "Since 2020, the city built 12 km of bike lanes. Bike accidents fell 20%, but downtown shops complain about 200 removed parking spots.",
    q: "Plainte des commerçants ?", qEn: "Shops' complaint?",
    choices: ["200 places de parking supprimées", "Trop de vélos", "Pistes dangereuses", "Baisse des clients à pied"],
    choicesEn: ["200 parking spots removed", "Too many bikes", "Dangerous lanes", "Fewer walk-in clients"],
    answer: 0, explain: "Suppression de deux cents places.", explainFr: "Suppression de deux cents places." },
  { n: 38, section: "F", type: "mcq", doc: "PR4", title: "Language / Langue", titleFr: "Langue", level: "B2",
    text: "Selon une étude, les adultes qui pratiquent dix minutes de français par jour progressent deux fois plus vite que ceux qui étudient deux heures le week-end. La régularité bat la quantité.",
    textEn: "Per a study, adults practising ten minutes of French daily progress twice as fast as weekend two-hour studiers. Regularity beats quantity.",
    q: "Conclusion de l'étude ?", qEn: "Study conclusion?",
    choices: ["La régularité bat la quantité", "Il faut étudier le week-end", "10 minutes ne servent à rien", "Seuls les enfants progressent"],
    choicesEn: ["Regularity beats quantity", "Study on weekends", "10 minutes is useless", "Only children progress"],
    answer: 0, explain: "Dernière phrase = thèse.", explainFr: "Dernière phrase = thèse." },
  { n: 39, section: "F", type: "mcq", doc: "PR4", title: "Language / Langue", titleFr: "Langue", level: "B2",
    text: "Selon une étude, les adultes qui pratiquent dix minutes de français par jour progressent deux fois plus vite que ceux qui étudient deux heures le week-end. La régularité bat la quantité.",
    textEn: "Per a study, adults practising ten minutes of French daily progress twice as fast as weekend two-hour studiers. Regularity beats quantity.",
    q: "Qui progresse le plus vite ?", qEn: "Who progresses fastest?",
    choices: ["10 min par jour", "2 h le week-end", "Aucune pratique", "1 h par mois"],
    choicesEn: ["10 min daily", "2h weekends", "No practice", "1h monthly"],
    answer: 0, explain: "Deux fois plus vite.", explainFr: "Deux fois plus vite." },
  { n: 40, section: "F", type: "mcq", doc: "PR4", title: "Language / Langue", titleFr: "Langue", level: "B2",
    text: "Selon une étude, les adultes qui pratiquent dix minutes de français par jour progressent deux fois plus vite que ceux qui étudient deux heures le week-end. La régularité bat la quantité.",
    textEn: "Per a study, adults practising ten minutes of French daily progress twice as fast as weekend two-hour studiers. Regularity beats quantity.",
    q: "« Battre » signifie ici ?", qEn: "What does 'bat' mean here?",
    choices: ["Être meilleur que", "Frapper", "Jouer", "Cuisiner"],
    choicesEn: ["To outperform", "To hit", "To play", "To cook"],
    answer: 0, explain: "Vocab-in-context: la régularité l'emporte.", explainFr: "Vocab en contexte : la régularité l'emporte." },
];

// ---- Writing: exam-style (A = fact sheet → article, B = opinion) ----
export const writingPromptsA = [
  { fr: "Faits : colis n°4582 reçu hier, boîte ouverte, un article manque, photos jointes. Écrivez au service client (80 mots min).", en: "Facts: parcel #4582 received yesterday, box open, one item missing, photos attached. Write to customer service (80+ words)." },
  { fr: "Faits : portefeuille perdu dans un taxi vendredi soir, trajet gare-hôtel, portefeuille noir. Écrivez à la compagnie (80 mots min).", en: "Facts: wallet lost in a taxi Friday night, station-hotel ride, black wallet. Write to the company (80+ words)." },
  { fr: "Faits : cours de cuisine samedi, 12 participants, chef sympathique, plat raté mais soirée drôle. Racontez (80 mots min).", en: "Facts: cooking class Saturday, 12 people, nice chef, failed dish but funny evening. Tell the story (80+ words)." },
  { fr: "Faits : voisin bruit chaque nuit depuis 2 semaines, musique après minuit, déjà demandé une fois. Écrivez-lui (80 mots min).", en: "Facts: noisy neighbour every night for 2 weeks, music after midnight, asked once already. Write to them (80+ words)." },
  { fr: "Faits : abonnement salle de sport 40 €/mois, déménagement dans 1 mois, préavis d'un mois. Demandez la résiliation (80 mots min).", en: "Facts: gym membership €40/month, moving in 1 month, one-month notice. Request cancellation (80+ words)." },
  { fr: "Faits : week-end à Montréal, train annulé, auberge complète, rencontré des amis, concert improvisé. Racontez (80 mots min).", en: "Facts: weekend in Montreal, train cancelled, hostel full, met friends, improvised concert. Tell the story (80+ words)." },
];

export const writingPromptsB = [
  { fr: "Un journal publie : « La voiture n'a plus sa place en centre-ville ». Écrivez une lettre formelle au rédacteur pour défendre votre avis (200 mots min).", en: "A paper claims: 'Cars no longer belong downtown.' Write a formal letter to the editor defending your stance (200+ words)." },
  { fr: "Un éditorial dit : « Le télétravail isole les salariés ». Écrivez au rédacteur pour justifier votre position (200 mots min).", en: "An editorial says: 'Remote work isolates employees.' Write to the editor justifying your position (200+ words)." },
  { fr: "Un journal affirme : « Les écrans nuisent aux enfants ». Écrivez une lettre formelle au rédacteur avec vos arguments (200 mots min).", en: "A paper claims: 'Screens harm children.' Write a formal letter to the editor with your arguments (200+ words)." },
  { fr: "Un éditorial déclare : « Sans français, impossible de s'intégrer au Canada ». Écrivez au rédacteur pour défendre votre avis (200 mots min).", en: "An editorial says: 'Without French, integrating in Canada is impossible.' Write to the editor defending your view (200+ words)." },
  { fr: "Un journal écrit : « Les cours en ligne sont inefficaces ». Écrivez une lettre formelle au rédacteur pour justifier votre stance (200 mots min).", en: "A paper writes: 'Online classes don't work.' Write a formal letter to the editor justifying your stance (200+ words)." },
  { fr: "Un éditorial propose : « Passons à la semaine de 4 jours ». Écrivez au rédacteur pour défendre votre position (200 mots min).", en: "An editorial proposes: 'Let's switch to a 4-day week.' Write to the editor defending your position (200+ words)." },
];

// ---- Speaking A: real-ad based (ad + ask task) ----
export const speakingPromptsA = [
  { title: "Apartment for rent", titleFr: "Appartement à louer",
    ad: "T2 45 m² proche métro, 950 € + 50 € charges. Libre 1er mars. Agence Fontaine, visites sur rendez-vous.",
    adEn: "1-bed 45m² near metro, €950 + €50 charges. Free March 1. Fontaine agency, viewings by appointment.",
    role: "You call the agency. Ask 10 formal questions: rent, charges, size, transport, availability, visit, documents, contact.",
    roleFr: "Vous appelez l'agence. Posez 10 questions formelles : loyer, charges, surface, transport, disponibilité, visite, documents." },
  { title: "French course", titleFr: "Cours de français",
    ad: "Français B2, mardi et jeudi 18h, 200 € le trimestre. Inscriptions avant le 15 octobre, 20 places par groupe.",
    adEn: "French B2, Tue + Thu 6pm, €200/term. Register before Oct 15, 20 places per group.",
    role: "You call the school. Ask about: schedule, price, level test, registration, certificate, cancellation.",
    roleFr: "Vous appelez l'école. Demandez : horaires, prix, test de niveau, inscription, attestation, annulation." },
  { title: "Hotel in Quebec", titleFr: "Hôtel à Québec",
    ad: "Hôtel Vieux-Port : 120 €/nuit, petit-déjeuner 15 €, parking 20 €/jour. Annulation gratuite 48h avant.",
    adEn: "Vieux-Port hotel: €120/night, breakfast €15, parking €20/day. Free cancellation 48h before.",
    role: "You call the hotel. Ask about: price, breakfast, parking, cancellation, late arrival, rooms, transport.",
    roleFr: "Vous appelez l'hôtel. Demandez : prix, petit-déjeuner, parking, annulation, arrivée tardive, chambres, transport." },
  { title: "Job interview", titleFr: "Emploi",
    ad: "Serveur/serveuse, week-end uniquement, 1 an d'expérience. Envoyez CV + lettre avant le 30. Restaurant Le Quai.",
    adEn: "Waiter/waitress, weekends only, 1 year experience. Send CV + letter before the 30th. Le Quai restaurant.",
    role: "You call the restaurant. Ask about: position, hours, salary, contract, experience, start date, contact.",
    roleFr: "Vous appelez le restaurant. Demandez : poste, horaires, salaire, contrat, expérience, début, contact." },
  { title: "Tennis club", titleFr: "Club de tennis",
    ad: "Inscriptions mercredi 14h–17h au gymnase. Certificat médical récent exigé. Tarif : 80 € l'année.",
    adEn: "Registration Wednesday 2–5pm at the gym. Recent medical certificate required. Fee: €80/year.",
    role: "You call the club. Ask about: registration, documents, price, schedule, levels, trial, equipment.",
    roleFr: "Vous appelez le club. Demandez : inscription, documents, prix, horaires, niveaux, essai, équipement." },
];

export const speakingPromptsB = [
  { title: "Convince a friend", titleFr: "Convaincre un ami", role: "Convince a friend to join an evening French class with you.", roleFr: "Convainquez un ami de s'inscrire avec vous à un cours de français du soir." },
  { title: "Neighbourhood party", titleFr: "Association", role: "Convince the town hall to fund a street party.", roleFr: "Convainquez la mairie de financer une fête de quartier." },
  { title: "Remote work", titleFr: "Télétravail", role: "Convince your manager to let you work from home 2 days a week.", roleFr: "Convainquez votre manager de vous laisser télétravailler 2 jours/semaine." },
  { title: "Holiday", titleFr: "Voyage", role: "Convince your family to holiday in Canada instead of the beach.", roleFr: "Convainquez votre famille de passer les vacances au Canada plutôt qu'à la plage." },
  { title: "Sport", titleFr: "Sport", role: "Convince a colleague to exercise with you at lunch.", roleFr: "Convainquez un collègue de faire du sport avec vous le midi." },
];

export const questionStems = [
  { fr: "Quel est le prix / le tarif exact ?", en: "What is the exact price?" },
  { fr: "Est-ce que les charges sont comprises ?", en: "Are charges included?" },
  { fr: "Quelle est la surface / la superficie ?", en: "What is the size?" },
  { fr: "C'est disponible à partir de quand ?", en: "Available from when?" },
  { fr: "Y a-t-il des transports en commun à proximité ?", en: "Is there public transport nearby?" },
  { fr: "Quels documents faut-il fournir ?", en: "Which documents are required?" },
  { fr: "Quelle est la date limite d'inscription ?", en: "What is the registration deadline?" },
  { fr: "Est-ce qu'il y a des frais supplémentaires ?", en: "Are there extra fees?" },
  { fr: "C'est ouvert quels jours et à quelles heures ?", en: "Which days/hours is it open?" },
  { fr: "Est-ce possible d'annuler / de reporter ?", en: "Can I cancel / postpone?" },
  { fr: "Quel est le délai de remboursement ?", en: "What is the refund delay?" },
  { fr: "Faut-il réserver à l'avance ?", en: "Must I book in advance?" },
  { fr: "Y a-t-il une réduction pour les étudiants ?", en: "Is there a student discount?" },
  { fr: "Combien de temps dure la formation ?", en: "How long is the training?" },
  { fr: "Qui dois-je contacter en cas de problème ?", en: "Who do I contact if there is a problem?" },
  { fr: "Pouvez-vous me préciser les horaires ?", en: "Could you confirm the schedule?" },
  { fr: "Y a-t-il un parking à proximité ?", en: "Is there parking nearby?" },
  { fr: "Proposez-vous une visite / un essai gratuit ?", en: "Do you offer a free visit / trial?" },
  { fr: "Comment se passe l'inscription étape par étape ?", en: "How does registration work step by step?" },
  { fr: "Le petit-déjeuner est-il inclus ?", en: "Is breakfast included?" },
];

export const connecteurs = {
  "Structure / Structurer": [
    { fr: "Premièrement", en: "Firstly" }, { fr: "Deuxièmement", en: "Secondly" },
    { fr: "Enfin", en: "Finally" }, { fr: "Pour conclure", en: "To conclude" }, { fr: "En résumé", en: "In summary" },
  ],
  "Add / Ajouter": [
    { fr: "De plus", en: "Moreover" }, { fr: "En outre", en: "Besides" },
    { fr: "Également", en: "Also" }, { fr: "Par ailleurs", en: "Furthermore" },
  ],
  "Contrast / Opposer": [
    { fr: "Cependant", en: "However" }, { fr: "Pourtant", en: "Yet" },
    { fr: "Néanmoins", en: "Nevertheless" }, { fr: "En revanche", en: "On the other hand" },
    { fr: "Bien que + subjonctif", en: "Although + subjunctive" },
  ],
  "Cause": [
    { fr: "Car", en: "For/because" }, { fr: "Parce que", en: "Because" },
    { fr: "Grâce à", en: "Thanks to" }, { fr: "À cause de", en: "Because of (neg.)" },
  ],
  "Consequence / Conséquence": [
    { fr: "Donc", en: "So" }, { fr: "C'est pourquoi", en: "That's why" },
    { fr: "Par conséquent", en: "Consequently" }, { fr: "Ainsi", en: "Thus" },
  ],
  "Opinion": [
    { fr: "À mon avis", en: "In my opinion" }, { fr: "Selon moi", en: "According to me" },
    { fr: "Il est essentiel de", en: "It is essential to" }, { fr: "Je suis convaincu(e) que", en: "I am convinced that" },
  ],
};

export const vocabBook = [
  { fr: "bénéficier de", en: "to benefit from", ex: "Vous bénéficiez d'une remise.", exEn: "You get a discount.", tag: "High freq" },
  { fr: "supérieur à", en: "greater than", ex: "Un achat supérieur à 50 €.", exEn: "A purchase over €50.", tag: "High freq" },
  { fr: "en raison de", en: "due to", ex: "En raison de travaux.", exEn: "Due to works.", tag: "High freq" },
  { fr: "prendre rendez-vous", en: "to make an appointment", ex: "Je voudrais prendre rendez-vous.", exEn: "I'd like to make an appointment.", tag: "Section A" },
  { fr: "les charges comprises", en: "charges included", ex: "950 € charges comprises.", exEn: "€950 including charges.", tag: "Housing" },
  { fr: "la date butoir", en: "the deadline", ex: "La date butoir est le 15 octobre.", exEn: "The deadline is Oct 15.", tag: "Studies" },
  { fr: "un levier", en: "a lever / driver", ex: "Un levier de productivité.", exEn: "A productivity driver.", tag: "B2" },
  { fr: "la cohésion", en: "cohesion", ex: "La cohésion d'équipe.", exEn: "Team cohesion.", tag: "B2" },
  { fr: "les éclaircies", en: "sunny spells", ex: "Avec des éclaircies.", exEn: "With sunny spells.", tag: "Weather" },
  { fr: "le point relais", en: "pickup point", ex: "Votre colis est au point relais.", exEn: "Your parcel is at the pickup point.", tag: "Service" },
  { fr: "le remboursement", en: "refund", ex: "Quel est le délai de remboursement ?", exEn: "What is the refund delay?", tag: "Section A" },
  { fr: "y compris", en: "including", ex: "Y compris le certificat.", exEn: "Including the certificate.", tag: "Reading" },
];

export const sampleWritingA = `Objet : Damaged parcel – refund request / Colis endommagé

Madame, Monsieur,
J'ai reçu hier le colis n°4582, mais il est arrivé endommagé : la boîte était ouverte et un article manque. (Yesterday I received parcel #4582, but it arrived damaged.)
Premièrement, je vous joins les photos. De plus, le livreur n'a pas attendu ma signature. (First, photos attached. Moreover, the driver did not wait.)
C'est pourquoi je demande un remboursement ou un renvoi rapide. (That is why I request a quick refund or reshipment.)
En vous remerciant par avance, cordialement. Léa (96 words)`;

export const sampleWritingB = `Monsieur le Rédacteur, / Dear Editor,

J'ai lu avec intérêt votre éditorial sur la voiture en centre-ville, et je souhaite défendre un avis favorable à son interdiction progressive. (I read your editorial on cars downtown, and I wish to defend a view in favour of phasing them out.)
Premièrement, cela réduit la pollution. Par exemple, à Montréal, la qualité de l'air s'est améliorée grâce aux zones piétonnes. De plus, c'est plus sûr pour les piétons et les vélos. (Firstly it cuts pollution. For example... Moreover, it is safer.)
Cependant, certains objectent que les commerces souffriront. Bien qu'il faille les aider avec des parkings relais et plus de bus, cet argument ne justifie pas le statu quo. (However, some object that shops will suffer. Although we must help them...)
En conclusion, je vous remercie de publier ce point de vue : interdire progressivement la voiture, tout en proposant des alternatives, est la meilleure solution. (In conclusion, thank you for publishing this view...)
Je vous prie d'agréer, Monsieur le Rédacteur, l'expression de mes salutations distinguées. Léa — expand to 200+ words on exam day.`;

export const dailyPlan = [
  { day: "Monday", dayFr: "Lundi", focus: "Listening A–C (Q1–14)", focusFr: "Écoute A–C (Q1–14)", time: "30 min", task: "Pictures + announcements + answering machine" },
  { day: "Tuesday", dayFr: "Mardi", focus: "Reading A–B (Q1–17)", focusFr: "Lecture A–B (Q1–17)", time: "30 min", task: "Doc matching + completions" },
  { day: "Wednesday", dayFr: "Mercredi", focus: "Writing A – fact-sheet article", focusFr: "Écrit A – article à partir des faits", time: "40 min", task: "1 timed text 80+ words" },
  { day: "Thursday", dayFr: "Jeudi", focus: "Speaking A – ad-based questions", focusFr: "Oral A – questions sur annonce", time: "30 min", task: "2 recorded role-plays" },
  { day: "Friday", dayFr: "Vendredi", focus: "Listening D–G (Q15–40)", focusFr: "Écoute D–G (Q15–40)", time: "40 min", task: "Opinions + interviews + report" },
  { day: "Saturday", dayFr: "Samedi", focus: "Writing B + Speaking B", focusFr: "Écrit B + Oral B", time: "60 min", task: "1 essay 200 words + 1 argument" },
  { day: "Sunday", dayFr: "Dimanche", focus: "Full mock in exam order", focusFr: "Mock complet dans l'ordre", time: "90 min", task: "Listening 40 + Reading 40" },
];

export const connecteurDuJour = [
  { fr: "Bien que + subjonctif", ex: "Bien qu'il soit difficile, je continue.", en: "Although (it is hard, I continue)" },
  { fr: "Grâce à", ex: "Grâce à ce cours, j'ai progressé.", en: "Thanks to (this course, I improved)" },
  { fr: "C'est pourquoi", ex: "Il pleut, c'est pourquoi je reste.", en: "That's why (it's raining, so I stay)" },
  { fr: "En revanche", ex: "Il est cher, en revanche il est fiable.", en: "On the other hand (expensive but reliable)" },
  { fr: "Par conséquent", ex: "Il a plu, par conséquent le match est annulé.", en: "Consequently (it rained, match cancelled)" },
  { fr: "À mon avis", ex: "À mon avis, c'est essentiel.", en: "In my opinion (it's essential)" },
  { fr: "De plus", ex: "C'est utile, de plus c'est gratuit.", en: "Moreover (useful and free)" },
];
